CREATE TABLE student (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    surname VARCHAR(64) NOT NULL

);

CREATE TABLE teacher (

    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64),
    surname VARCHAR(64),
    username VARCHAR(64),
    password VARCHAR(60)

);

CREATE TABLE evaluation (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream VARCHAR(64) NOT NULL,
    student BIGINT REFERENCES student(id),
    teacher BIGINT REFERENCES teacher(id),
    communication_grade TINYINT NOT NULL,
    communication_comments VARCHAR(255),
    is_extramile BOOLEAN NOT NULL,
    is_extramile_comments VARCHAR(255),
    is_motivated BOOLEAN NOT NULL,
    motivation_comments VARCHAR(255),
    direction_comments VARCHAR(255),
    ability_to_learn_grade TINYINT NOT NULL,
    ability_to_learn_comments VARCHAR(255),
    overall_comments VARCHAR(255),
    created_at DATE NOT NULL,
    updated_at DATE NOT NULL

);